--------------------------------------------------------
--  DDL for Table FEED_FROM_UWWB
--------------------------------------------------------

  CREATE TABLE "CAP_ST"."FEED_FROM_UWWB" 
   (	"NODE_TYPE" VARCHAR2(100 BYTE), 
	"OBJECT_TYPE_ID" NUMBER, 
	"VARIABLE_ID" NUMBER, 
	"NODE_NAME" VARCHAR2(4000 BYTE), 
	"VARIABLE_VALUE" VARCHAR2(4000 BYTE), 
	"FEED_POLICY_NUMBER" VARCHAR2(100 BYTE), 
	"FILLIN_TYPE" VARCHAR2(500 BYTE), 
	"IMPORT_DATE" DATE DEFAULT SYSDATE, 
	"DRAGON_VAR_NAME" VARCHAR2(500 BYTE), 
	"PRIMARY_CLASS_ENUM" NUMBER(*,0), 
	"SEC_CLASS_ENUM" NUMBER(*,0), 
	"DROP_AT_RENEWAL" VARCHAR2(500 BYTE), 
	"FORM_ISSUE_ONLY" VARCHAR2(500 BYTE), 
	"TRANSLATED_FORM_CODE" VARCHAR2(500 BYTE), 
	"IMPORTED" VARCHAR2(50 BYTE), 
	"SUBID" NUMBER(*,0), 
	"PTP_ID" NUMBER(*,0), 
	"PICKED_UP" VARCHAR2(50 BYTE), 
	"SRC_FILE" VARCHAR2(500 BYTE), 
	"ENDTNUM" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORAGE_DATA" ;
--------------------------------------------------------
--  Constraints for Table FEED_FROM_UWWB
--------------------------------------------------------

  ALTER TABLE "CAP_ST"."FEED_FROM_UWWB" MODIFY ("FEED_POLICY_NUMBER" NOT NULL ENABLE);
